export const TENSION_PATTERNS = [
    /finally revealing/gi,
    /the real reason/gi,
    /darker truth/gi,
    /the truth is/gi,
    /what they don't want you to know/gi,
    /the hidden side of/gi,
    /dropped a bombshell/gi,
    /reveals everything/gi,
    /what happened next/gi,
    /we need to go back/gi,
    /was just the beginning/gi,
    /everything was about to change/gi,
    /little did (?:he|she|they|we) know/gi,
    /the unthinkable happened/gi,
    /took a (?:strange|dark|weird) turn/gi,
    /what we're about to explore/gi,
    /will show you/gi,
    /even more (?:damaging|shocking|surprising|interesting)/gi,
    /gets even (?:worse|better|stranger)/gi,
    /pales in comparison/gi,
    /most (?:devastating|damaging|shocking|disgusting)/gi,
    /the story gets even more/gi,
    /but that's not all/gi,
    /there's a catch/gi,
    /the answer might surprise you/gi,
    /what happens next will shock you/gi,
    /just when you think/gi,
    /but what if/gi,
    /but to understand why/gi
  ];